#x[begin:end] = The begin index is included in the slice, the end index is not. 

x = list["a", "b", "c", "d"]
x[1]
x[-3] # same result!

#result = b

# Create the areas list
areas = ["hallway", 11.25, "kitchen", 18.0, "living room", 20.0, "bedroom", 10.75, "bathroom", 9.50]

#Print out the second element from the areas list, so 11.25.
print(areas[1])

#Subset and print out the last element of areas, being 9.50. Using a negative index makes sense here!
print(areas[-1]

#Select the number representing the area of the living room and print it out.
